@BASE_URL=http://localhost:3000
@CHAT_ID=68e0ffdcf8406590b9e58f97

### Create chat by FriendId
POST {{BASE_URL}}/chats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTY5OWNhNzJjYzA1MTgxYjNhZTg3NCIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoiUmF0ZSIsImlhdCI6MTc2MDAyNjM3OH0.8DJaeA7MsFlRr_oQDnHHg4l-kBZpG5zlPMw4vtAOSFE

{
  "friendId": "68e7ad64b40c24c8918e4e05"
}

### Find chat by user id
GET {{BASE_URL}}/chats/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTY5OWNhNzJjYzA1MTgxYjNhZTg3NCIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoiUmF0ZSIsImlhdCI6MTc2MDAyNjM3OH0.8DJaeA7MsFlRr_oQDnHHg4l-kBZpG5zlPMw4vtAOSFE

### Find all chats

GET {{BASE_URL}}/chats/all
Content-Type: application/json

### Delete chat by ID

DELETE {{BASE_URL}}/chats/delete/{{CHAT_ID}}
Content-Type: application/json