@BASE_URL=http://localhost:3000


### Register User

POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "username": "toni",
  "email": "toni@tes.com",
  "password": "strongpassword"
}

### Login User

POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
 "email": "toni@test.com",
  "password": "strongpassword"
}

### Get all users

GET {{BASE_URL}}/user/others
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTY5OWNhNzJjYzA1MTgxYjNhZTg3NCIsImVtYWlsIjoidG9uaUB0ZXN0LmNvbSIsInVzZXJuYW1lIjoiUmF0ZSIsImlhdCI6MTc2MDAxNDQ5N30.-8h414pfePyPKtSsrj7Uk6dKlXskqvENFe_2Iah2ZvQ

