@BASE_URL=http://localhost:3000

### Check the token and allow access

GET {{BASE_URL}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGQ0MGZiMjczY2UwNDM4ZjllY2UwMiIsImVtYWlsIjoidG9uaUBleGFtcC5jb20iLCJpYXQiOjE3NTk0MDU5OTN9.579qBw4IOTSZ7NvgkXctYoBP7V2HDdrSTtkPVRHEexw

### Register User

POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
  "username": "toni",
  "email": "toni@tes.com",
  "password": "strongpassword"
}

### Login User

POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
 "email": "toni@test.com",
  "password": "strongpassword"
}

### Get all users

GET {{BASE_URL}}/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGI3N2M0ZGVjMTEwODYwY2U2YTA2ZiIsImVtYWlsIjoidG9uaUBleGFtcC5jb20iLCJpYXQiOjE3NTkyMzI3OTJ9.DhuMGz_3HPG-P8W6LDo_xO7isqWe1RVWRji6G4B_BRc


